flowchart TB
    User([HR/Manager/Leader])
    
    subgraph "10.0 Thống kê"
        direction TB
        
        SC[get_statistics_scope]
        SU[get_scope_users]
        SF[build_statistics_filters]
        TR[get_time_range_from_params]
        
        subgraph "Thu thập dữ liệu"
            BD1[build_statistics_records]
            BD2[build_evaluation_records]
            BD3[build_rewards_penalties_records]
        end
        
        FR1[filter_statistics_records]
        FR2[filter_evaluation_records_by_time]
        FR3[filter_rewards_records_by_time]
        
        SM[build_statistics_summary_rows]
        ES[build_evaluation_statistics_sections]
        RS[build_rewards_statistics_sections]
        BS[build_statistics_sections]
        
        OUT1[Render web template]
        OUT2[Export Excel - openpyxl]
        OUT3[Render print template]
    end
    
    D4[(AttendanceRecord)]
    D5[(LeaveRequest)]
    D6[(OvertimeRequest)]
    D7[(Evaluation)]
    D8[(RewardPenalty)]
    
    User --> SC
    SC --> SU
    SU --> SF
    User --> TR
    
    SF --> BD1
    BD1 -->|read| D4
    BD1 -->|read| D5
    BD1 -->|read| D6
    SF --> BD2
    BD2 -->|read| D7
    SF --> BD3
    BD3 -->|read| D8
    
    BD1 --> FR1
    BD2 --> FR2
    BD3 --> FR3
    TR --> FR1
    TR --> FR2
    TR --> FR3
    
    FR1 --> SM
    FR2 --> ES
    FR3 --> RS
    
    SM --> BS
    ES --> BS
    RS --> BS
    
    BS --> OUT1
    BS --> OUT2
    BS --> OUT3
