# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('reward', 'Khen thưởng'), ('penalty', 'Xử phạt')], help_text='Loại: khen thưởng hay xử phạt.', max_length=10)),
                ('amount', models.PositiveIntegerField(default=0, help_text='Số tiền thưởng/phạt (VND).')),
                ('reason_title', models.CharField(help_text='Tiêu đề lý do.', max_length=255)),
                ('reason_detail', models.TextField(blank=True, default='', help_text='Chi tiết lý do.')),
                ('status', models.CharField(default='pending', help_text='Trạng thái: pending, approved, rejected.', max_length=20)),
                ('application_date', models.DateField(help_text='Ngày áp dụng.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='Nhân viên được thưởng/phạt.', on_delete=django.db.models.deletion.CASCADE, related_name='rewards_penalties', to=settings.AUTH_USER_MODEL)),
                ('proposer', models.ForeignKey(blank=True, help_text='Người đề xuất.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_rewards_penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khen thưởng / Xử phạt',
                'verbose_name_plural': 'Khen thưởng / Xử phạt',
                'ordering': ['-application_date'],
            },
        ),
    ]
