# Generated by Django 4.2 on 2026-05-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_discipline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpenalty',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Tài liệu/File minh chứng đính kèm.', null=True, upload_to='reward_evidence/'),
        ),
    ]
