# Generated by Django 4.2 on 2026-06-02 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards_discipline', '0002_rewardpenalty_evidence_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpenalty',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='HR duyệt cấp 2 (cuối).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_l2_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardpenalty',
            name='leader_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardpenalty',
            name='leader_approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager duyệt cấp 1 (nếu Leader lập phiếu).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_l1_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rewardpenalty',
            name='status',
            field=models.CharField(default='pending', help_text='Trạng thái duyệt: pending → leader_approved → approved / rejected.', max_length=20),
        ),
    ]
