# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(help_text='Ngày chấm công.')),
                ('check_in_time', models.TimeField(blank=True, help_text='Giờ vào làm.', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Giờ tan làm.', null=True)),
                ('status', models.CharField(blank=True, default='', help_text='Trạng thái: on_time, late, absent...', max_length=20)),
                ('user', models.ForeignKey(help_text='Nhân viên sở hữu bản ghi chấm công.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bản ghi chấm công',
                'verbose_name_plural': 'Bản ghi chấm công',
                'ordering': ['-record_date'],
                'unique_together': {('user', 'record_date')},
            },
        ),
    ]
