# Generated by Django 4.2 on 2026-05-21 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_base64', models.TextField(help_text='Chuỗi base64 của ảnh khuôn mặt nhân viên.')),
                ('content_type', models.CharField(default='image/png', help_text='MIME type của ảnh gốc. VD: image/jpeg, image/png.', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật ảnh lần cuối.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo bản ghi.')),
                ('user', models.OneToOneField(help_text='Nhân viên sở hữu ảnh khuôn mặt này.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_face', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ảnh khuôn mặt nhân viên',
                'verbose_name_plural': 'Ảnh khuôn mặt nhân viên',
            },
        ),
    ]
