# Generated by Django 4.2 on 2026-05-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employeeface'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeface',
            name='slot_id',
            field=models.PositiveSmallIntegerField(default=1, help_text='FastAPI slot ID (1-5). Pinned to 1 for now; field exists so multi-slot is non-migration.'),
        ),
    ]
