# Generated by Django 4.2 on 2026-05-27 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_employeeface_slot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('forgot', 'Quên chấm ra'), ('technical', 'Lỗi kỹ thuật / hệ thống'), ('business_trip', 'Đi công tác / ra ngoài làm việc'), ('other', 'Khác')], max_length=20)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('claimed_check_out_time', models.TimeField(help_text='Giờ ra thực tế nhân viên khai báo.')),
                ('evidence', models.FileField(blank=True, help_text='Ảnh / PDF chứng từ tùy chọn.', null=True, upload_to='attendance/adjustments/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Chờ HR duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_note', models.TextField(blank=True, default='')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_request', to='attendance.attendancerecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu điều chỉnh chấm công',
                'verbose_name_plural': 'Yêu cầu điều chỉnh chấm công',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
