# Generated by Django 4.2 on 2026-05-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendanceadjustmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeface',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector khuôn mặt (512 chiều) từ InsightFace.', null=True),
        ),
    ]
