# Generated by Django 4.2 on 2026-06-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_employeeface_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceadjustmentrequest',
            name='claimed_check_in_time',
            field=models.TimeField(blank=True, help_text='Giờ vào thực tế nhân viên khai báo (nếu cần sửa).', null=True),
        ),
        migrations.AlterField(
            model_name='attendanceadjustmentrequest',
            name='claimed_check_out_time',
            field=models.TimeField(blank=True, help_text='Giờ ra thực tế nhân viên khai báo (nếu cần sửa).', null=True),
        ),
    ]
