# Generated by Django 4.2 on 2026-06-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendanceadjustmentrequest_claimed_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceadjustmentrequest',
            name='evidence',
            field=models.FileField(blank=True, help_text='Ảnh / PDF chứng từ.', null=True, upload_to='attendance/adjustments/%Y/%m/'),
        ),
    ]
