# Generated by Django 4.2 on 2026-06-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendanceadjustmentrequest_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeface',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='employeeface',
            name='face_base64',
            field=models.TextField(help_text='Chuỗi base64 của ảnh khuôn mặt (preview).'),
        ),
        migrations.AlterField(
            model_name='employeeface',
            name='slot_id',
            field=models.PositiveSmallIntegerField(default=1, help_text='Slot trên service từ xa (1-5). Hiện pin về 1.'),
        ),
    ]
