# Generated by Django 4.2 on 2026-06-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0008_remove_employeeface_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField(help_text='Ảnh khuôn mặt chờ duyệt (base64).')),
                ('content_type', models.CharField(default='image/jpeg', max_length=50)),
                ('image_sha256', models.CharField(blank=True, default='', help_text='SHA-256 của ảnh — phục vụ audit / phát hiện đảo ảnh.', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ HR duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='Người thực hiện cập nhật (để phát hiện đổi mặt hộ người khác).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Nhân viên chủ khuôn mặt sẽ được cập nhật.', on_delete=django.db.models.deletion.CASCADE, related_name='face_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu cập nhật khuôn mặt',
                'verbose_name_plural': 'Yêu cầu cập nhật khuôn mặt',
                'ordering': ['-created_at'],
            },
        ),
    ]
