# Generated by Django 4.2 on 2026-06-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0009_facechangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeface',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='employeeface',
            name='face_base64',
        ),
        migrations.RemoveField(
            model_name='facechangerequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='facechangerequest',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='facechangerequest',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh khuôn mặt chờ duyệt (Cloudinary ở prod). Approve → xóa; reject → giữ làm minh chứng.', null=True, upload_to='face_changes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='employeeface',
            name='user',
            field=models.OneToOneField(help_text='Nhân viên sở hữu bản ghi khuôn mặt này.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_face', to=settings.AUTH_USER_MODEL),
        ),
    ]
