# Generated by Django 4.2 on 2026-06-03 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_employeeface_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(default=datetime.time(8, 30), help_text='Giờ bắt đầu làm việc chuẩn.')),
                ('shift_end', models.TimeField(default=datetime.time(17, 30), help_text='Giờ kết thúc ca làm chuẩn.')),
                ('late_grace_minutes', models.PositiveIntegerField(default=5, help_text="Số phút ân hạn đi trễ trước khi tính 'late'.")),
            ],
            options={
                'verbose_name': 'Cấu hình giờ làm',
                'verbose_name_plural': 'Cấu hình giờ làm',
            },
        ),
    ]
