# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="Mã quyền (VD: 'can_export_reports').", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Tên hiển thị (VD: 'Xuất báo cáo').", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Giải thích quyền này cho phép làm gì.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('manager', 'Manager'), ('leader', 'Leader'), ('employee', 'Employee')], help_text="Tên vai trò (VD: 'admin', 'manager').", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Mô tả vai trò này làm gì.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', help_text='Họ tên đầy đủ.', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Số điện thoại.', max_length=20)),
                ('date_of_birth', models.CharField(blank=True, default='', help_text='Ngày sinh (DD/MM/YYYY).', max_length=10)),
                ('employee_id', models.CharField(blank=True, help_text='Mã nhân viên duy nhất.', max_length=50, null=True, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Quyền tùy chỉnh, tách riêng khỏi role.', related_name='users', to='accounts.custompermission')),
                ('role', models.ForeignKey(blank=True, help_text='Vai trò hệ thống. Quyết định giao diện và quyền truy cập.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
                ('user', models.OneToOneField(help_text='Django user mà profile này thuộc về.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
