# Generated by Django 6.0.3 on 2026-03-25 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="A short code for this permission (e.g., 'can_export_reports').", max_length=100, unique=True)),
                ('name', models.CharField(help_text="A human-readable name (e.g., 'Can Export Reports').", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Explains what this permission allows the user to do.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('master', 'Master'), ('manager', 'Manager'), ('leader', 'Leader'), ('employee', 'Employee')], help_text="The role name (e.g., 'master', 'manager').", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='A human-readable description of what this role does.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Custom permissions assigned to this user, independent of role.', related_name='users', to='accounts.custompermission')),
                ('role', models.ForeignKey(blank=True, help_text="The user's role. Determines UI behavior.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
                ('user', models.OneToOneField(help_text='The Django user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
