# Generated by Django 6.0.3 on 2026-03-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', help_text='Date of birth in DD/MM/YYYY format.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique employee ID. Each ID can only be used for one account.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text="User's full name (no numbers or special characters).", max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number (digits only).', max_length=20),
        ),
    ]
