# Generated by Django 6.0.3 on 2026-05-04 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_date_of_birth_userprofile_employee_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Department or business unit managed by HR/Admin.', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leader_user',
            field=models.ForeignKey(blank=True, help_text='Direct leader of this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_user',
            field=models.ForeignKey(blank=True, help_text='Direct manager of this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='', help_text='Job title managed by HR/Admin.', max_length=100),
        ),
    ]
