# Generated by Django 4.2 on 2026-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_use_auth_user_email_move_personal_info'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='userprofile_employee_id_not_blank',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Full name from registration.', max_length=255, null=True),
        ),
    ]
