# Generated by Django 6.0.3 on 2026-05-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_department_userprofile_leader_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('manager', 'Manager'), ('leader', 'Leader'), ('employee', 'Employee')], help_text="The role name (e.g., 'master', 'manager').", max_length=50, unique=True),
        ),
    ]
