# Generated by Django 6.0.3 on 2026-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_type',
            field=models.CharField(blank=True, default='', help_text='Employee type such as Full-time, Part-time or Intern.', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='official_start_date',
            field=models.CharField(blank=True, default='', help_text='Official working date in DD/MM/YYYY format.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='probation_start',
            field=models.CharField(blank=True, default='', help_text='Probation start date in DD/MM/YYYY format.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_status',
            field=models.CharField(blank=True, choices=[('working', 'Đang làm việc'), ('probation', 'Đang thử việc'), ('paused', 'Tạm nghỉ'), ('resigned', 'Đã nghỉ việc')], default='', help_text='Current working status managed by HR/Admin.', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workplace',
            field=models.CharField(blank=True, default='', help_text='Main workplace or office location.', max_length=100),
        ),
    ]
