# Generated by Django 6.0.3 on 2026-05-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_employee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contract_annual_leave_days',
            field=models.PositiveIntegerField(blank=True, help_text='Annual leave days defined in the current contract.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contract_attachment_reference',
            field=models.CharField(blank=True, default='', help_text='File name or link reference for the current contract attachment.', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contract_end_date',
            field=models.CharField(blank=True, default='', help_text='Contract end date in DD/MM/YYYY format. Leave blank for open-ended contracts.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contract_number',
            field=models.CharField(blank=True, default='', help_text='Current contract number managed by HR/Admin.', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contract_signed_date',
            field=models.CharField(blank=True, default='', help_text='Contract signed date in DD/MM/YYYY format.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contract_standard_shift',
            field=models.CharField(blank=True, default='', help_text='Standard shift described in the current contract.', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contract_start_date',
            field=models.CharField(blank=True, default='', help_text='Contract effective start date in DD/MM/YYYY format.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contract_type',
            field=models.CharField(blank=True, default='', help_text='Current contract type such as probation or official contract.', max_length=100),
        ),
    ]
