# Generated by Codex on 2026-07-03

from django.db import migrations, models


def seed_company_configuration(apps, schema_editor):
    CompanyConfiguration = apps.get_model('accounts', 'CompanyConfiguration')
    CompanyConfiguration.objects.get_or_create(pk=1)


def unseed_company_configuration(apps, schema_editor):
    CompanyConfiguration = apps.get_model('accounts', 'CompanyConfiguration')
    CompanyConfiguration.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplaces', models.TextField(default='Văn phòng Hà Nội\nVăn phòng TP.HCM\nVăn phòng Đà Nẵng\nRemote\nHybrid', help_text='Danh sách nơi làm việc, mỗi dòng một giá trị.')),
                ('contract_types', models.TextField(default='Thử việc\nXác định thời hạn\nKhông xác định thời hạn\nThời vụ', help_text='Danh sách loại hợp đồng lao động, mỗi dòng một giá trị.')),
                ('reward_policy', models.TextField(default='Thưởng theo thành tích hoàn thành vượt chỉ tiêu.\nThưởng đột xuất cho đóng góp nổi bật được quản lý/HR xác nhận.\nMức thưởng cụ thể do HR duyệt theo ngân sách và minh chứng kèm theo.', help_text='Cơ chế khen thưởng nội bộ.')),
                ('penalty_policy', models.TextField(default='Xử phạt vi phạm nội quy sau khi có minh chứng hoặc biên bản xác nhận.\nMức phạt căn cứ theo mức độ ảnh hưởng và quy định nội bộ hiện hành.\nNhân viên được thông báo lý do trước khi phiếu xử phạt được áp dụng.', help_text='Cơ chế xử phạt nội bộ.')),
                ('departments', models.TextField(default='Nhân sự\nKinh doanh\nKế toán\nCông nghệ thông tin\nMarketing\nVận hành', help_text='Danh sách phòng ban, mỗi dòng một giá trị.')),
                ('positions', models.TextField(default='Nhân viên\nChuyên viên\nTrưởng nhóm\nQuản lý\nTrưởng phòng', help_text='Danh sách chức vụ, mỗi dòng một giá trị.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình công ty',
                'verbose_name_plural': 'Cấu hình công ty',
            },
        ),
        migrations.RunPython(seed_company_configuration, unseed_company_configuration),
    ]
