# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, default='', help_text='Loại nghỉ: phép năm, ốm, việc riêng...', max_length=50)),
                ('start_date', models.DateField(help_text='Ngày bắt đầu nghỉ.')),
                ('end_date', models.DateField(help_text='Ngày kết thúc nghỉ.')),
                ('reason', models.TextField(blank=True, default='', help_text='Lý do nghỉ phép.')),
                ('status', models.CharField(default='pending', help_text='Trạng thái: pending, approved, rejected.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Người phê duyệt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Nhân viên gửi đơn nghỉ phép.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn nghỉ phép',
                'verbose_name_plural': 'Đơn nghỉ phép',
                'ordering': ['-created_at'],
            },
        ),
    ]
