# Generated by Django 4.2 on 2026-05-17 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Số ngày nghỉ.', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leader_approved_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm duyệt bước 1.', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leader_approved_by',
            field=models.ForeignKey(blank=True, help_text='Leader/Manager đã duyệt bước 1.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rejected_reason',
            field=models.TextField(blank=True, default='', help_text='Lý do từ chối (nếu bị từ chối).'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Người phê duyệt cuối cùng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Nghỉ phép năm'), ('sick', 'Nghỉ ốm'), ('personal', 'Nghỉ việc riêng'), ('maternity', 'Nghỉ thai sản'), ('business', 'Công tác'), ('other', 'Khác')], default='annual', help_text='Loại nghỉ: phép năm, ốm, việc riêng...', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('leader_approved', 'Quản lý đã duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', help_text='Trạng thái đơn.', max_length=20),
        ),
    ]
