# Generated by Django 4.2 on 2026-06-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_days_leaverequest_leader_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Tệp minh chứng (PDF/JPG/PNG, ≤5MB).', null=True, upload_to='leaves/attachments/%Y/%m/'),
        ),
    ]
