# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(blank=True, default='', help_text='Loại nhân viên: Toàn thời gian, Bán thời gian, Thực tập...', max_length=100)),
                ('department', models.CharField(blank=True, default='', help_text='Phòng ban hoặc bộ phận. VD: Phòng Kinh doanh.', max_length=100)),
                ('position', models.CharField(blank=True, default='', help_text='Chức danh. VD: Chuyên viên kinh doanh.', max_length=100)),
                ('workplace', models.CharField(blank=True, default='', help_text='Nơi làm việc chính. VD: Văn phòng Hà Nội.', max_length=100)),
                ('probation_start', models.CharField(blank=True, default='', help_text='Ngày bắt đầu thử việc (DD/MM/YYYY).', max_length=10)),
                ('official_start_date', models.CharField(blank=True, default='', help_text='Ngày làm việc chính thức (DD/MM/YYYY).', max_length=10)),
                ('work_status', models.CharField(blank=True, choices=[('working', 'Đang làm việc'), ('probation', 'Đang thử việc'), ('paused', 'Tạm nghỉ'), ('resigned', 'Đã nghỉ việc')], default='', help_text='Trạng thái làm việc hiện tại.', max_length=30)),
                ('leader_user', models.ForeignKey(blank=True, help_text='Leader phụ trách nhân viên này.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_employees', to=settings.AUTH_USER_MODEL)),
                ('manager_user', models.ForeignKey(blank=True, help_text='Quản lý trực tiếp của nhân viên này.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User sở hữu thông tin công việc này.', on_delete=django.db.models.deletion.CASCADE, related_name='work_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông tin công việc',
                'verbose_name_plural': 'Thông tin công việc',
                'ordering': ['user__username'],
            },
        ),
    ]
