# Generated by Django 4.2 on 2026-05-16 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_profiles', '0002_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, default='', help_text='Giới tính', max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='id_card_issue_date',
            field=models.CharField(blank=True, default='', help_text='Ngày cấp (DD/MM/YYYY)', max_length=10),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='id_card_issue_place',
            field=models.CharField(blank=True, default='', help_text='Nơi cấp', max_length=255),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='id_card_number',
            field=models.CharField(blank=True, default='', help_text='Số CCCD/CMND', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='marital_status',
            field=models.CharField(blank=True, default='', help_text='Tình trạng hôn nhân', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(blank=True, default='', help_text='Quốc tịch', max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='permanent_address',
            field=models.TextField(blank=True, default='', help_text='Địa chỉ thường trú'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='temporary_address',
            field=models.TextField(blank=True, default='', help_text='Địa chỉ tạm trú'),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên hoặc tiêu đề minh chứng', max_length=255)),
                ('document_type', models.CharField(blank=True, default='', help_text='Loại minh chứng (VD: Bằng cấp, CCCD)', max_length=100)),
                ('file', models.FileField(help_text='Tệp đính kèm', upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tải lên')),
                ('user', models.ForeignKey(help_text='Nhân viên sở hữu tệp này.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, default='', help_text='Họ tên người liên hệ', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', help_text='Số điện thoại', max_length=20)),
                ('relation', models.CharField(blank=True, default='', help_text='Quan hệ với nhân viên', max_length=100)),
                ('contact_address', models.TextField(blank=True, default='', help_text='Địa chỉ')),
                ('user', models.OneToOneField(help_text='Nhân viên sở hữu thông tin liên hệ này.', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationAndSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, default='', help_text='Trình độ học vấn', max_length=100)),
                ('degree', models.CharField(blank=True, default='', help_text='Bằng cấp', max_length=255)),
                ('major', models.CharField(blank=True, default='', help_text='Chuyên ngành', max_length=255)),
                ('certificates', models.TextField(blank=True, default='', help_text='Chứng chỉ')),
                ('foreign_languages', models.TextField(blank=True, default='', help_text='Ngoại ngữ')),
                ('professional_skills', models.TextField(blank=True, default='', help_text='Kỹ năng chuyên môn')),
                ('user', models.OneToOneField(help_text='Nhân viên sở hữu hồ sơ năng lực này.', on_delete=django.db.models.deletion.CASCADE, related_name='education_and_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
