# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(help_text='Ngày đánh giá.')),
                ('content', models.TextField(help_text='Nội dung đánh giá.')),
                ('evidence_reference', models.CharField(blank=True, default='', help_text='File minh chứng hoặc link tham chiếu.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='Nhân viên được đánh giá.', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='Người thực hiện đánh giá (Manager/Leader).', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá nhân viên',
                'verbose_name_plural': 'Đánh giá nhân viên',
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
