"""
Django settings for business_web project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-oi6-@*vsp#h4u2z)lz1)(v^xdm)%40soejx0uw3=byorpw=uj_',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Comma-separated list từ env. Mặc định cho dev local.
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
).split(',')

CSRF_TRUSTED_ORIGINS = [
    o for o in config('CSRF_TRUSTED_ORIGINS', default='').split(',') if o
]

# Render tự inject hostname thật → auto-allow, khỏi lo đặt sai tên.
_RENDER_HOST = config('RENDER_EXTERNAL_HOSTNAME', default='')
if _RENDER_HOST:
    ALLOWED_HOSTS.append(_RENDER_HOST)
    CSRF_TRUSTED_ORIGINS.append(f'https://{_RENDER_HOST}')

# Bảo mật prod (chỉ bật khi DEBUG=False). Render kết thúc SSL ở proxy.
if not DEBUG:
    # Chặn deploy với SECRET_KEY yếu. Tiêu chí giống Django security.W009:
    # prefix 'django-insecure-', dài < 50, hoặc < 5 ký tự khác nhau.
    # Prod PHẢI đặt SECRET_KEY mạnh qua biến môi trường.
    if (
        SECRET_KEY.startswith('django-insecure-')
        or len(SECRET_KEY) < 50
        or len(set(SECRET_KEY)) < 5
    ):
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            'SECRET_KEY không an toàn cho production (mặc định/quá ngắn/ít ngẫu nhiên). '
            'Đặt biến môi trường SECRET_KEY bằng một chuỗi ngẫu nhiên đủ dài (≥50 ký tự).'
        )
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 năm
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # cloudinary cho MEDIA → phải đứng SAU staticfiles, nếu không lệnh
    # collectstatic của cloudinary_storage đè lệnh Django và copy 0 file.
    'cloudinary_storage',
    'cloudinary',
    # ----- Project apps -----
    'accounts',              # Auth, dashboard, admin user management
    'employee_profiles',     # Hồ sơ nhân viên
    'contracts',             # Hợp đồng lao động
    'attendance',            # Chấm công
    'leaves',                # Nghỉ phép
    'overtime',              # Tăng ca
    'performance',           # Đánh giá nhân viên
    'rewards_discipline',    # Khen thưởng & Xử phạt
    'reports_interactions',  # Báo cáo & Tương tác
    'stats_reports',         # Thống kê tổng hợp
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'business_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'business_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Dùng DATABASE_URL (Postgres trên Render) nếu có, fallback SQLite local.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Add path for login, sign up account
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# =============================================================================
# SESSION (QĐ_Session) — tự đăng xuất sau 30 phút KHÔNG hoạt động.
#   SESSION_SAVE_EVERY_REQUEST=True làm mới hạn cookie mỗi request → đếm theo
#   thời gian *không hoạt động* thay vì thời gian từ lúc đăng nhập.
# =============================================================================
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', default=1800, cast=int)  # 30 phút
SESSION_SAVE_EVERY_REQUEST = True

# =============================================================================
# LOGIN LOCKOUT (QĐ_TK1) — sai mật khẩu N lần liên tiếp → khóa tài khoản
#   (is_active=False). Mở khóa do HR/Admin (QĐ_TK2). Đếm trong cache, không
#   thêm model. Cửa sổ đếm reset sau LOGIN_LOCKOUT_WINDOW_SEC nếu ngừng thử.
# =============================================================================
LOGIN_LOCKOUT_MAX_FAILS = config('LOGIN_LOCKOUT_MAX_FAILS', default=3, cast=int)
LOGIN_LOCKOUT_WINDOW_SEC = config('LOGIN_LOCKOUT_WINDOW_SEC', default=900, cast=int)

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (avatar, uploads, minh chứng chấm công)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# STORAGE
#   - static: WhiteNoise (nén + hash, serve trực tiếp từ web service)
#   - media : Cloudinary khi USE_CLOUDINARY=True (file sống sót qua redeploy),
#             ngược lại lưu local disk (dev).
#   Dùng RawMediaCloudinaryStorage vì field evidence nhận cả ẢNH lẫn PDF.
# =============================================================================
USE_CLOUDINARY = config('USE_CLOUDINARY', default=False, cast=bool)

STORAGES = {
    'default': {
        'BACKEND': (
            'cloudinary_storage.storage.RawMediaCloudinaryStorage'
            if USE_CLOUDINARY
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        # Default storage; WhiteNoise middleware lo serve + cache headers.
        # Không dùng Compressed/Manifest storage để tránh lỗi post-process
        # (admin sorting-icons.svg manifest-strict + bug đường dẫn unicode).
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

if USE_CLOUDINARY:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': config('CLOUDINARY_API_KEY'),
        'API_SECRET': config('CLOUDINARY_API_SECRET'),
    }

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# EMAIL - Gmail SMTP (đọc từ file .env)
# =============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# =============================================================================
# FACE RECOGNITION / ATTENDANCE
# =============================================================================
from datetime import time as _time

# Remote face-recognition API (register + recognize). All AI/matching runs there.
FACE_API_BASE_URL = config(
    'FACE_API_BASE_URL',
    default='https://kluan-facial-recognition-for-attendance-tracking.hf.space',
).rstrip('/')
FACE_API_TIMEOUT_SEC = config('FACE_API_TIMEOUT_SEC', default=30, cast=int)

FACE_LOCKOUT_MAX_FAILS = config('FACE_LOCKOUT_MAX_FAILS', default=3, cast=int)
FACE_LOCKOUT_DURATION_SEC = config('FACE_LOCKOUT_DURATION_SEC', default=300, cast=int)
WORK_START_TIME = _time(8, 30)
WORK_END_TIME = _time(17, 30)
WORK_LATE_GRACE_MIN = config('WORK_LATE_GRACE_MIN', default=5, cast=int)

