# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề báo cáo.', max_length=255)),
                ('content', models.TextField(help_text='Nội dung báo cáo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='Người gửi báo cáo.', on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('support', 'Hỗ trợ'), ('complaint', 'Khiếu nại')], default='support', help_text='Loại: hỗ trợ hay khiếu nại.', max_length=20)),
                ('title', models.CharField(help_text='Tiêu đề ticket.', max_length=255)),
                ('content', models.TextField(help_text='Nội dung chi tiết.')),
                ('status', models.CharField(default='open', help_text='Trạng thái: open, processing, closed.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Người xử lý ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(help_text='Người tạo ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
