# Generated by Django 4.2 on 2026-05-18 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports_interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_viewed',
            field=models.BooleanField(default=False, help_text='Trạng thái đã xem của cấp quản lý.'),
        ),
        migrations.AddField(
            model_name='report',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Quản lý nhận báo cáo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm quản lý xem báo cáo.', null=True),
        ),
    ]
