# Generated by Django 4.2 on 2026-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_interactions', '0002_report_is_viewed_report_recipient_report_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='Tài liệu/file đính kèm.', null=True, upload_to='report_attachments/'),
        ),
    ]
