# Generated by Django 4.2 on 2026-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_interactions', '0003_report_file_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='File minh chứng đính kèm.', null=True, upload_to='tickets/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], default='medium', help_text='Mức độ ưu tiên.', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Lý do từ chối (nếu có).', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('processing', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('closed', 'Đã đóng'), ('rejected', 'Bị từ chối')], default='new', help_text='Trạng thái của ticket.', max_length=20),
        ),
    ]
