# Generated by Django 4.2 on 2026-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_interactions', '0004_ticket_evidence_file_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='manager_note',
            field=models.TextField(blank=True, default='', help_text='Phản hồi/chỉ đạo của quản lý.'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('submitted', 'Đã gửi'), ('needs_update', 'Yêu cầu cập nhật'), ('acknowledged', 'Đã tiếp nhận')], default='submitted', help_text='Trạng thái nghiệp vụ của báo cáo.', max_length=20),
        ),
    ]
