# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_date', models.DateField(help_text='Ngày tăng ca.')),
                ('hours', models.DecimalField(decimal_places=1, help_text='Số giờ tăng ca.', max_digits=4)),
                ('reason', models.TextField(blank=True, default='', help_text='Lý do tăng ca.')),
                ('status', models.CharField(default='pending', help_text='Trạng thái: pending, approved, rejected.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Người phê duyệt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Nhân viên đăng ký tăng ca.', on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn tăng ca',
                'verbose_name_plural': 'Đơn tăng ca',
                'ordering': ['-created_at'],
            },
        ),
    ]
