# Generated by Django 4.2 on 2026-05-17 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Giờ kết thúc tăng ca.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='rejected_reason',
            field=models.TextField(blank=True, default='', help_text='Lý do từ chối (nếu bị từ chối).'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='start_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Giờ bắt đầu tăng ca.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', help_text='Trạng thái: pending, approved, rejected.', max_length=20),
        ),
    ]
