# Generated by Django 4.2 on 2026-05-17 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtime', '0002_overtimerequest_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='leader_approved_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm duyệt bước 1.', null=True),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='leader_approved_by',
            field=models.ForeignKey(blank=True, help_text='Leader/Manager đã duyệt bước 1.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_approved_overtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Người phê duyệt cuối cùng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('leader_approved', 'Quản lý đã duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', help_text='Trạng thái đơn.', max_length=20),
        ),
    ]
