# Generated by Django 4.2 on 2026-06-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_overtimerequest_leader_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Tệp minh chứng (PDF/JPG/PNG, ≤5MB).', null=True, upload_to='overtime/attachments/%Y/%m/'),
        ),
    ]
