# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, default='', help_text='Số hợp đồng hiện tại. VD: HD-2026-001.', max_length=100)),
                ('contract_type', models.CharField(blank=True, default='', help_text='Loại hợp đồng. VD: Thử việc 2 tháng, Chính thức 1 năm.', max_length=100)),
                ('contract_signed_date', models.CharField(blank=True, default='', help_text='Ngày ký hợp đồng (DD/MM/YYYY).', max_length=10)),
                ('contract_start_date', models.CharField(blank=True, default='', help_text='Ngày bắt đầu hiệu lực (DD/MM/YYYY).', max_length=10)),
                ('contract_end_date', models.CharField(blank=True, default='', help_text='Ngày hết hạn (DD/MM/YYYY). Để trống nếu không thời hạn.', max_length=10)),
                ('contract_annual_leave_days', models.PositiveIntegerField(blank=True, help_text='Số ngày nghỉ phép/năm theo hợp đồng.', null=True)),
                ('contract_standard_shift', models.CharField(blank=True, default='', help_text='Ca làm tiêu chuẩn. VD: 08:30 - 17:30 (Thứ 2 đến Thứ 6).', max_length=100)),
                ('contract_attachment_reference', models.CharField(blank=True, default='', help_text='Tên file hoặc link tham chiếu hợp đồng.', max_length=255)),
                ('user', models.OneToOneField(help_text='User sở hữu hợp đồng này.', on_delete=django.db.models.deletion.CASCADE, related_name='contract_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hợp đồng lao động',
                'verbose_name_plural': 'Hợp đồng lao động',
                'ordering': ['user__username'],
            },
        ),
    ]
