# Generated by Django 4.2 on 2026-06-01 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinfo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Hợp đồng đang hiệu lực?'),
        ),
        migrations.AddField(
            model_name='contractinfo',
            name='shift_end_time',
            field=models.TimeField(blank=True, help_text='Giờ kết thúc ca (về sớm tính từ đây).', null=True),
        ),
        migrations.AddField(
            model_name='contractinfo',
            name='shift_start_time',
            field=models.TimeField(blank=True, help_text='Giờ bắt đầu ca (đi trễ tính từ đây).', null=True),
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='user',
            field=models.ForeignKey(help_text='Nhân viên sở hữu hợp đồng này.', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
