# Generated by Django 4.2 on 2026-06-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractinfo_is_active_contractinfo_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo bản HĐ này (dùng cho lịch sử).', null=True),
        ),
    ]
